/**
 * Standardized error codes for the application
 * Format: DOMAIN_SPECIFIC_ERROR
 */
export enum ErrorCode {
  // Authentication errors
  AUTH_EMAIL_CONFIRMATION_REQUIRED = 'AUTH_EMAIL_CONFIRMATION_REQUIRED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_ALREADY_EXISTS = 'AUTH_USER_ALREADY_EXISTS',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_ACCOUNT_CREATION_FAILED = 'AUTH_ACCOUNT_CREATION_FAILED',

  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // User errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_UPDATE_FAILED = 'USER_UPDATE_FAILED',

  // Server errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  // Generic errors
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
}