/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  DeepNonNullable
} from '@orval/core';

import type {
  ClubControllerFindAllParams,
  ClubResponseDto,
  CreateClubDto,
  UpdateClubDto
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';

@Injectable({ providedIn: 'root' })
export class ClubsService {
  private readonly http = inject(HttpClient);
/**
 * @summary Create a new club
 */
 clubControllerCreate<TData = ClubResponseDto>(
    createClubDto: CreateClubDto,
 ) {
      return customInstance<TData>(
      {url: `/api/clubs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createClubDto
    },
      this.http,
      );
    }
  /**
 * @summary Get all clubs with pagination and filtering
 */
 clubControllerFindAll<TData = void>(
    params?: DeepNonNullable<ClubControllerFindAllParams>,
 ) {
      return customInstance<TData>(
      {url: `/api/clubs`, method: 'GET',
        params
    },
      this.http,
      );
    }
  /**
 * @summary Get a club by ID
 */
 clubControllerFindOne<TData = ClubResponseDto>(
    id: string,
 ) {
      return customInstance<TData>(
      {url: `/api/clubs/${id}`, method: 'GET'
    },
      this.http,
      );
    }
  /**
 * @summary Update a club
 */
 clubControllerUpdate<TData = ClubResponseDto>(
    id: string,
    updateClubDto: UpdateClubDto,
 ) {
      return customInstance<TData>(
      {url: `/api/clubs/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateClubDto
    },
      this.http,
      );
    }
  /**
 * @summary Delete a club
 */
 clubControllerRemove<TData = void>(
    id: string,
 ) {
      return customInstance<TData>(
      {url: `/api/clubs/${id}`, method: 'DELETE'
    },
      this.http,
      );
    }
  };

export type ClubControllerCreateClientResult = NonNullable<ClubResponseDto>
export type ClubControllerFindAllClientResult = NonNullable<void>
export type ClubControllerFindOneClientResult = NonNullable<ClubResponseDto>
export type ClubControllerUpdateClientResult = NonNullable<ClubResponseDto>
export type ClubControllerRemoveClientResult = NonNullable<void>
