/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  AuthResponseDto,
  SignInDto,
  SignUpDto,
  UpdateProfileDto,
  UserDto
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';






@Injectable({ providedIn: 'root' })
export class AuthenticationService {
  private readonly http = inject(HttpClient);
/**
 * @summary Sign up a new user
 */
 authControllerSignUp<TData = AuthResponseDto>(
    signUpDto: SignUpDto,
 ) {
      return customInstance<TData>(
      {url: `/api/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signUpDto
    },
      this.http,
      );
    }
  /**
 * @summary Sign in an existing user
 */
 authControllerSignIn<TData = AuthResponseDto>(
    signInDto: SignInDto,
 ) {
      return customInstance<TData>(
      {url: `/api/auth/signin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signInDto
    },
      this.http,
      );
    }
  /**
 * @summary Sign out the current user
 */
 authControllerSignOut<TData = void>(
    
 ) {
      return customInstance<TData>(
      {url: `/api/auth/signout`, method: 'POST'
    },
      this.http,
      );
    }
  /**
 * @summary Get current user profile
 */
 authControllerGetProfile<TData = UserDto>(
    
 ) {
      return customInstance<TData>(
      {url: `/api/auth/profile`, method: 'GET'
    },
      this.http,
      );
    }
  /**
 * @summary Update current user profile
 */
 authControllerUpdateProfile<TData = UserDto>(
    updateProfileDto: UpdateProfileDto,
 ) {
      return customInstance<TData>(
      {url: `/api/auth/profile`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProfileDto
    },
      this.http,
      );
    }
  }

export type AuthControllerSignUpClientResult = NonNullable<AuthResponseDto>
export type AuthControllerSignInClientResult = NonNullable<AuthResponseDto>
export type AuthControllerSignOutClientResult = NonNullable<void>
export type AuthControllerGetProfileClientResult = NonNullable<UserDto>
export type AuthControllerUpdateProfileClientResult = NonNullable<UserDto>
