/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  ObservationResponseDto,
  UpsertObservationDto
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';






@Injectable({ providedIn: 'root' })
export class ObservationsService {
  private readonly http = inject(HttpClient);
/**
 * @summary Upsert observation for a phase (create or update)
 */
 observationControllerUpsert<TData = ObservationResponseDto>(
    tastingId: string,
    phase: string,
    upsertObservationDto: UpsertObservationDto,
 ) {
      return customInstance<TData>(
      {url: `/api/tastings/${tastingId}/observations/${phase}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertObservationDto
    },
      this.http,
      );
    }
  /**
 * @summary Delete observation for a phase
 */
 observationControllerRemove<TData = void>(
    tastingId: string,
    phase: string,
 ) {
      return customInstance<TData>(
      {url: `/api/tastings/${tastingId}/observations/${phase}`, method: 'DELETE'
    },
      this.http,
      );
    }
  /**
 * @summary Get all observations for a tasting
 */
 observationControllerFindAll<TData = ObservationResponseDto[]>(
    tastingId: string,
 ) {
      return customInstance<TData>(
      {url: `/api/tastings/${tastingId}/observations`, method: 'GET'
    },
      this.http,
      );
    }
  };

export type ObservationControllerUpsertClientResult = NonNullable<ObservationResponseDto>
export type ObservationControllerRemoveClientResult = NonNullable<void>
export type ObservationControllerFindAllClientResult = NonNullable<ObservationResponseDto[]>
