/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  CigarResponseDto,
  CreateCigarDto
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';






@Injectable({ providedIn: 'root' })
export class CigarsService {
  private readonly http = inject(HttpClient);
/**
 * @summary Get cigar by slug (public)
 */
 cigarControllerFindBySlug<TData = CigarResponseDto>(
    slug: string,
 ) {
      return customInstance<TData>(
      {url: `/api/cigars/${slug}`, method: 'GET'
    },
      this.http,
      );
    }
  /**
 * @summary Create a new cigar (with inline brand creation)
 */
 cigarControllerCreate<TData = CigarResponseDto>(
    createCigarDto: CreateCigarDto,
 ) {
      return customInstance<TData>(
      {url: `/api/cigars`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCigarDto
    },
      this.http,
      );
    }
  };

export type CigarControllerFindBySlugClientResult = NonNullable<CigarResponseDto>
export type CigarControllerCreateClientResult = NonNullable<CigarResponseDto>
