/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';






@Injectable({ providedIn: 'root' })
export class AppService {
  private readonly http = inject(HttpClient);
 appControllerGetData<TData = void>(
    
 ) {
      return customInstance<TData>(
      {url: `/api`, method: 'GET'
    },
      this.http,
      );
    }
  };

export type AppControllerGetDataClientResult = NonNullable<void>
