/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  UpdateProfileDto,
  UsersControllerUploadAvatar200,
  UsersControllerUploadAvatarBody
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';

@Injectable({ providedIn: 'root' })
export class UsersService {
  private readonly http = inject(HttpClient);
/**
 * @summary Update current user profile
 */
 usersControllerUpdateProfile<TData = void>(
    updateProfileDto: UpdateProfileDto,
 ) {
      return customInstance<TData>(
      {url: `/api/users/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProfileDto
    },
      this.http,
      );
    }
  /**
 * @summary Upload user avatar
 */
 usersControllerUploadAvatar<TData = UsersControllerUploadAvatar200>(
    usersControllerUploadAvatarBody: UsersControllerUploadAvatarBody,
 ) {const formData = new FormData();
if(usersControllerUploadAvatarBody.avatar !== undefined) {
 formData.append(`avatar`, usersControllerUploadAvatarBody.avatar)
 }

      return customInstance<TData>(
      {url: `/api/users/me/avatar`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      this.http,
      );
    }
  }

export type UsersControllerUpdateProfileClientResult = NonNullable<void>
export type UsersControllerUploadAvatarClientResult = NonNullable<UsersControllerUploadAvatar200>
