/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  DeepNonNullable
} from '@orval/core';

import type {
  ClubResponseDto,
  UpdateProfileDto,
  UserPublicProfileDto,
  UsersControllerCheckUsernameAvailability200,
  UsersControllerCheckUsernameAvailabilityParams,
  UsersControllerGetUserClubsParams,
  UsersControllerUploadAvatar200,
  UsersControllerUploadAvatarBody
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';






@Injectable({ providedIn: 'root' })
export class UsersService {
  private readonly http = inject(HttpClient);
/**
 * @summary Get user public profile with stats
 */
 usersControllerGetPublicProfile<TData = UserPublicProfileDto>(
    identifier: string,
 ) {
      return customInstance<TData>(
      {url: `/api/users/${identifier}/profile`, method: 'GET'
    },
      this.http,
      );
    }
  /**
 * @summary Get user's public clubs
 */
 usersControllerGetUserClubs<TData = ClubResponseDto[]>(
    identifier: string,
    params?: DeepNonNullable<UsersControllerGetUserClubsParams>,
 ) {
      return customInstance<TData>(
      {url: `/api/users/${identifier}/clubs`, method: 'GET',
        params
    },
      this.http,
      );
    }
  /**
 * @summary Update current user profile
 */
 usersControllerUpdateProfile<TData = void>(
    updateProfileDto: UpdateProfileDto,
 ) {
      return customInstance<TData>(
      {url: `/api/users/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProfileDto
    },
      this.http,
      );
    }
  /**
 * @summary Upload user avatar
 */
 usersControllerUploadAvatar<TData = UsersControllerUploadAvatar200>(
    usersControllerUploadAvatarBody: UsersControllerUploadAvatarBody,
 ) {const formData = new FormData();
if(usersControllerUploadAvatarBody.avatar !== undefined) {
 formData.append(`avatar`, usersControllerUploadAvatarBody.avatar)
 }

      return customInstance<TData>(
      {url: `/api/users/me/avatar`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      this.http,
      );
    }
  /**
 * @summary Check if username is available
 */
 usersControllerCheckUsernameAvailability<TData = UsersControllerCheckUsernameAvailability200>(
    username: string,
    params?: DeepNonNullable<UsersControllerCheckUsernameAvailabilityParams>,
 ) {
      return customInstance<TData>(
      {url: `/api/users/check-username/${username}`, method: 'GET',
        params
    },
      this.http,
      );
    }
  };

export type UsersControllerGetPublicProfileClientResult = NonNullable<UserPublicProfileDto>
export type UsersControllerGetUserClubsClientResult = NonNullable<ClubResponseDto[]>
export type UsersControllerUpdateProfileClientResult = NonNullable<void>
export type UsersControllerUploadAvatarClientResult = NonNullable<UsersControllerUploadAvatar200>
export type UsersControllerCheckUsernameAvailabilityClientResult = NonNullable<UsersControllerCheckUsernameAvailability200>
