/**
 * Shared Types Library - ORVAL GENERATED
 *
 * Architecture (Best Practice 2025):
 * - ALL types are auto-generated from Swagger via Orval
 * - ZERO manual type duplication
 * - ZERO Prisma imports (browser-safe)
 * - Source of truth: API Swagger decorators
 *
 * Workflow:
 * 1. Update API controllers with @Api* decorators
 * 2. Run `npm run generate:api`
 * 3. Types automatically sync to frontend
 *
 * DO NOT EDIT MANUALLY - Run `npm run generate:api` instead
 */

// Orval-generated types and enums (from Swagger)
export * from './lib/generated-api.schemas';

// Orval-generated services
// NOTE: Services are NOT exported from barrel file to avoid API build errors
// Import services directly: import { ClubsService } from '@cigar-platform/types/lib/clubs/clubs.service';

// Backward compatibility aliases (old names → Orval generated names)
export type { UserDto as User } from './lib/generated-api.schemas';
export type { SignUpDto as SignUpRequest } from './lib/generated-api.schemas';
export type { SignInDto as SignInRequest } from './lib/generated-api.schemas';
export type { UpdateProfileDto as UpdateProfileRequest } from './lib/generated-api.schemas';
export type { ClubResponseDto as Club } from './lib/generated-api.schemas';
export type { CreateClubDto as CreateClubRequest } from './lib/generated-api.schemas';
export { UserDtoRole as Role } from './lib/generated-api.schemas';

// Business types (not generated by Orval)
export * from './models/auth-response.model';

// Error types (business logic, not generated)
export * from './error';
