/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  DeepNonNullable
} from '@orval/core';

import type {
  BrandControllerFindAllParams,
  BrandResponseDto
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';






@Injectable({ providedIn: 'root' })
export class BrandsService {
  private readonly http = inject(HttpClient);
/**
 * @summary Get all brands with optional search
 */
 brandControllerFindAll<TData = BrandResponseDto[]>(
    params?: DeepNonNullable<BrandControllerFindAllParams>,
 ) {
      return customInstance<TData>(
      {url: `/api/brands`, method: 'GET',
        params
    },
      this.http,
      );
    }
  };

export type BrandControllerFindAllClientResult = NonNullable<BrandResponseDto[]>
