/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
export interface SignUpDto {
  /** User email address */
  email: string;
  /**
   * User password (min 8 characters)
   * @minLength 8
   */
  password: string;
  /** User display name */
  displayName: string;
}

/**
 * The effective access level (FREE or PREMIUM)
 */
export type UserPlanDtoType = typeof UserPlanDtoType[keyof typeof UserPlanDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserPlanDtoType = {
  FREE: 'FREE',
  PREMIUM: 'PREMIUM',
} as const;

/**
 * How the user obtained this plan
 */
export type UserPlanDtoSource = typeof UserPlanDtoSource[keyof typeof UserPlanDtoSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserPlanDtoSource = {
  DEFAULT: 'DEFAULT',
  SUBSCRIPTION: 'SUBSCRIPTION',
  TRIAL: 'TRIAL',
  BETA: 'BETA',
  GIFT: 'GIFT',
  LIFETIME: 'LIFETIME',
} as const;

/**
 * Current status of the plan
 */
export type UserPlanDtoStatus = typeof UserPlanDtoStatus[keyof typeof UserPlanDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserPlanDtoStatus = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
} as const;

export interface UserPlanDto {
  id: string;
  userId: string;
  /** The effective access level (FREE or PREMIUM) */
  type: UserPlanDtoType;
  /** How the user obtained this plan */
  source: UserPlanDtoSource;
  /** Current status of the plan */
  status: UserPlanDtoStatus;
  /** When this plan started */
  startedAt: string;
  /** When this plan expires (null = never) */
  expiresAt?: string;
  /** Reason for gift/beta access */
  giftReason?: string;
  /** Whether the user currently has Premium access (considering expiration and grace period) */
  isPremium: boolean;
  /** User-friendly label for the plan */
  label: string;
  /** Days remaining until expiration (null if no expiration) */
  daysRemaining?: number;
  /** Whether the plan is expiring within 30 days */
  isExpiringSoon: boolean;
  /** Whether the user is in grace period (expired but still has access) */
  isInGracePeriod: boolean;
}

export type UserDtoVisibility = typeof UserDtoVisibility[keyof typeof UserDtoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDtoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
} as const;

export type UserDtoRole = typeof UserDtoRole[keyof typeof UserDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDtoRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  USER: 'USER',
} as const;

/**
 * Authentication provider (from Supabase metadata)
 */
export type UserDtoAuthProvider = typeof UserDtoAuthProvider[keyof typeof UserDtoAuthProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDtoAuthProvider = {
  google: 'google',
  apple: 'apple',
  email: 'email',
} as const;

export interface UserDto {
  id: string;
  email: string;
  displayName: string;
  username: string;
  avatarUrl?: string;
  bio?: string;
  visibility: UserDtoVisibility;
  shareEvaluationsPublicly: boolean;
  role: UserDtoRole;
  createdAt: string;
  /** Authentication provider (from Supabase metadata) */
  authProvider?: UserDtoAuthProvider;
  /** User subscription plan with computed fields (isPremium, label, etc.) */
  plan?: UserPlanDto;
}

/**
 * Supabase session with access token, refresh token, and expiry info
 */
export type AuthResponseDtoSession = { [key: string]: unknown };

export interface AuthResponseDto {
  user: UserDto;
  /** Supabase session with access token, refresh token, and expiry info */
  session: AuthResponseDtoSession;
}

export interface SignInDto {
  /** User email address */
  email: string;
  /** User password */
  password: string;
}

/**
 * Profile visibility - PUBLIC: displayName visible | PRIVATE: only @username visible
 */
export type UpdateProfileDtoVisibility = typeof UpdateProfileDtoVisibility[keyof typeof UpdateProfileDtoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateProfileDtoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
} as const;

export interface UpdateProfileDto {
  /** Display name of the user */
  displayName?: string;
  /** Avatar URL */
  avatarUrl?: string;
  /** User bio/description */
  bio?: string;
  /** Share evaluations publicly on user profile */
  shareEvaluationsPublicly?: boolean;
  /**
   * Username (unique identifier) - lowercase, alphanumeric + dots + underscores only
   * @minLength 3
   * @maxLength 30
   * @pattern ^[a-z0-9._]{3,30}$
   */
  username?: string;
  /** Profile visibility - PUBLIC: displayName visible | PRIVATE: only @username visible */
  visibility?: UpdateProfileDtoVisibility;
}

/**
 * Club visibility
 */
export type CreateClubDtoVisibility = typeof CreateClubDtoVisibility[keyof typeof CreateClubDtoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateClubDtoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
} as const;

export interface CreateClubDto {
  /**
   * Club name
   * @minLength 3
   * @maxLength 100
   */
  name: string;
  /**
   * Club description
   * @maxLength 1000
   */
  description?: string;
  /** Club avatar image URL */
  imageUrl?: string;
  /** Club cover image URL */
  coverUrl?: string;
  /** Club visibility */
  visibility?: CreateClubDtoVisibility;
  /** Auto-approve join requests */
  autoApproveMembers?: boolean;
  /** Allow members to invite others */
  allowMemberInvites?: boolean;
  /** Maximum number of members (null = unlimited) */
  maxMembers?: number;
  /** Show in public directory (even if PRIVATE) */
  isPublicDirectory?: boolean;
}

export type ClubResponseDtoVisibility = typeof ClubResponseDtoVisibility[keyof typeof ClubResponseDtoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClubResponseDtoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
} as const;

/**
 * Current user's status in relation to this club (member, pending, banned, or null if no relationship)
 */
export type ClubResponseDtoCurrentUserStatus = typeof ClubResponseDtoCurrentUserStatus[keyof typeof ClubResponseDtoCurrentUserStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClubResponseDtoCurrentUserStatus = {
  member: 'member',
  pending: 'pending',
  rejected: 'rejected',
  banned: 'banned',
} as const;

/**
 * Current user's role in this club (only present if currentUserStatus is MEMBER)
 */
export type ClubResponseDtoCurrentUserRole = typeof ClubResponseDtoCurrentUserRole[keyof typeof ClubResponseDtoCurrentUserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClubResponseDtoCurrentUserRole = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
} as const;

export interface ClubResponseDto {
  id: string;
  name: string;
  slug: string;
  description?: string;
  imageUrl?: string;
  coverUrl?: string;
  visibility: ClubResponseDtoVisibility;
  /** Only returned for club owners/admins */
  inviteCode?: string;
  isPublicDirectory: boolean;
  autoApproveMembers: boolean;
  allowMemberInvites: boolean;
  maxMembers?: number;
  isArchived: boolean;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  /** Total number of members in the club */
  memberCount: number;
  /** Current user's status in relation to this club (member, pending, banned, or null if no relationship) */
  currentUserStatus?: ClubResponseDtoCurrentUserStatus;
  /** Current user's role in this club (only present if currentUserStatus is MEMBER) */
  currentUserRole?: ClubResponseDtoCurrentUserRole;
}

export interface PaginationMetaDto {
  /** Total number of items */
  total: number;
  /** Current page number */
  page: number;
  /** Items per page */
  limit: number;
}

export interface PaginatedClubResponseDto {
  /** Array of clubs */
  data: ClubResponseDto[];
  /** Pagination metadata */
  meta: PaginationMetaDto;
}

export interface ClubParcoursStatsDto {
  /** Total number of tastings shared with club */
  tastingCount: number;
  /** Number of members */
  memberCount: number;
  /** Number of events */
  eventCount: number;
}

export interface AromaStatDto {
  /** Aroma name */
  name: string;
  /** Frequency percentage (0-100) */
  percentage: number;
}

export interface TerroirStatDto {
  /** Country name */
  country: string;
  /** ISO 3166-1 alpha-2 country code (lowercase) */
  code: string;
  /** Percentage of tastings from this country */
  percentage: number;
}

export interface JournalTastingUserDto {
  username: string;
  displayName: string;
  avatarUrl?: string;
}

export interface JournalTastingDto {
  id: string;
  /** Cigar name */
  cigarName: string;
  /** Brand name */
  brandName: string;
  /** Brand logo URL */
  brandLogoUrl?: string;
  /** Rating (0.5-5) */
  rating: number;
  /** Tasting date */
  date: string;
  /** Top 2-3 aromas from observations (null if no chronic observations) */
  aromas?: string[];
  /** User who made the tasting (for club context only) */
  user?: JournalTastingUserDto;
}

export interface ClubProfileStatsResponseDto {
  /** Club parcours stats */
  parcours: ClubParcoursStatsDto;
  /** Whether the club has chronic observation data (from Premium members) */
  hasChronicData: boolean;
  /** Number of chronic tastings contributing to signature (for transparency) */
  chronicTastingCount: number;
  /** Top 4 aromas aggregated from Premium members (null if no chronic data) */
  aromaSignature?: AromaStatDto[];
  /** Top 3 terroirs (null if no chronic data) */
  terroirs?: TerroirStatDto[];
  /** Last 3 completed tastings shared with the club */
  journal: JournalTastingDto[];
}

/**
 * Club visibility
 */
export type UpdateClubDtoVisibility = typeof UpdateClubDtoVisibility[keyof typeof UpdateClubDtoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateClubDtoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
} as const;

export interface UpdateClubDto {
  /**
   * Club name
   * @minLength 3
   * @maxLength 100
   */
  name?: string;
  /**
   * Club description
   * @maxLength 1000
   */
  description?: string;
  /** Club avatar image URL */
  imageUrl?: string;
  /** Club cover image URL */
  coverUrl?: string;
  /** Club visibility */
  visibility?: UpdateClubDtoVisibility;
  /** Auto-approve join requests */
  autoApproveMembers?: boolean;
  /** Allow members to invite others */
  allowMemberInvites?: boolean;
  /** Maximum number of members (null = unlimited) */
  maxMembers?: number;
  /** Show in public directory (even if PRIVATE) */
  isPublicDirectory?: boolean;
}

export interface MemberUserDto {
  id: string;
  displayName: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
}

export type ClubMemberResponseDtoRole = typeof ClubMemberResponseDtoRole[keyof typeof ClubMemberResponseDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClubMemberResponseDtoRole = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
} as const;

export interface ClubMemberResponseDto {
  id: string;
  clubId: string;
  userId: string;
  role: ClubMemberResponseDtoRole;
  joinedAt: string;
  user: MemberUserDto;
}

export interface PaginatedMemberResponseDto {
  /** Array of club members */
  data: ClubMemberResponseDto[];
  /** Pagination metadata */
  meta: PaginationMetaDto;
}

/**
 * New role for the member
 */
export type UpdateMemberRoleDtoRole = typeof UpdateMemberRoleDtoRole[keyof typeof UpdateMemberRoleDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateMemberRoleDtoRole = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
} as const;

export interface UpdateMemberRoleDto {
  /** New role for the member */
  role: UpdateMemberRoleDtoRole;
}

export interface TransferOwnershipDto {
  /** User ID of the new owner */
  newOwnerId: string;
}

export interface BanMemberDto {
  /**
   * Reason for banning the member
   * @maxLength 500
   */
  reason?: string;
}

export interface ClubBanResponseDto {
  id: string;
  clubId: string;
  userId: string;
  bannedBy: string;
  /** @nullable */
  reason: string | null;
  createdAt: string;
  /** Banned user details */
  user: MemberUserDto;
  /** User who performed the ban */
  bannedByUser: MemberUserDto;
}

export interface PaginatedBanResponseDto {
  /** Array of banned members */
  data: ClubBanResponseDto[];
  /** Pagination metadata */
  meta: PaginationMetaDto;
}

export interface CreateJoinRequestDto {
  /**
   * Optional message to club owner/admin
   * @maxLength 500
   */
  message?: string;
}

export interface JoinByCodeDto {
  /** Club invitation code */
  code?: string;
}

/**
 * The role assigned to the user in the club
 */
export type JoinByCodeResponseDtoRole = typeof JoinByCodeResponseDtoRole[keyof typeof JoinByCodeResponseDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JoinByCodeResponseDtoRole = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
} as const;

export interface JoinByCodeResponseDto {
  /** The club that was joined */
  club: ClubResponseDto;
  /** The role assigned to the user in the club */
  role: JoinByCodeResponseDtoRole;
}

export type ClubJoinRequestResponseDtoStatus = typeof ClubJoinRequestResponseDtoStatus[keyof typeof ClubJoinRequestResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClubJoinRequestResponseDtoStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export interface ClubJoinRequestResponseDto {
  id: string;
  clubId: string;
  userId: string;
  status: ClubJoinRequestResponseDtoStatus;
  /** @nullable */
  message: string | null;
  createdAt: string;
  updatedAt: string;
  /** User who requested to join */
  user: MemberUserDto;
}

export interface PaginatedJoinRequestResponseDto {
  /** Array of join requests */
  data: ClubJoinRequestResponseDto[];
  /** Pagination metadata */
  meta: PaginationMetaDto;
}

/**
 * Join request status
 */
export type UpdateJoinRequestDtoStatus = typeof UpdateJoinRequestDtoStatus[keyof typeof UpdateJoinRequestDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateJoinRequestDtoStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export interface UpdateJoinRequestDto {
  /** Join request status */
  status?: UpdateJoinRequestDtoStatus;
}

export interface ParcoursStatsDto {
  /** Total number of tastings */
  tastingCount: number;
  /** Number of unique brands tasted */
  brandCount: number;
  /** Number of unique terroirs/countries */
  terroirCount: number;
}

export interface UserProfileStatsResponseDto {
  /** Parcours stats */
  parcours: ParcoursStatsDto;
  /** Whether the user has Premium access (needed for frontend display logic) */
  isPremium: boolean;
  /** Whether the user has chronic observation data */
  hasChronicData: boolean;
  /** Top 4 aromas (null if not Premium or no chronic data) */
  aromaSignature?: AromaStatDto[];
  /** Top 3 terroirs (null if not Premium or no chronic data) */
  terroirs?: TerroirStatDto[];
  /** Last 3 completed tastings */
  journal: JournalTastingDto[];
}

export interface UserStatsDto {
  /** Total number of cigar evaluations by this user */
  evaluationCount: number;
  /** User's favorite cigar brand (most evaluated brand) */
  favoriteBrand?: string;
  /** Total number of clubs the user is member of */
  clubCount: number;
}

export type UserPublicProfileDtoVisibility = typeof UserPublicProfileDtoVisibility[keyof typeof UserPublicProfileDtoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserPublicProfileDtoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
} as const;

export interface UserPublicProfileDto {
  id: string;
  displayName: string;
  username: string;
  visibility: UserPublicProfileDtoVisibility;
  avatarUrl?: string;
  bio?: string;
  createdAt: string;
  /** User statistics (evaluations, clubs, favorite brand) */
  stats: UserStatsDto;
}

export interface BrandSearchItemDto {
  id: string;
  type: string;
  name: string;
  /** @nullable */
  slug: string | null;
  /** @nullable */
  imageUrl: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  metadata: string | null;
  country: string;
}

export interface CigarSearchItemDto {
  id: string;
  type: string;
  name: string;
  /** @nullable */
  slug: string | null;
  /** @nullable */
  imageUrl: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  metadata: string | null;
  brandName: string;
  vitola: string;
  size: string;
  /** Whether the cigar has been verified by an admin */
  isVerified: boolean;
}

export interface ClubSearchItemDto {
  id: string;
  type: string;
  name: string;
  /** @nullable */
  slug: string | null;
  /** @nullable */
  imageUrl: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  metadata: string | null;
  memberCount: number;
  visibility: string;
}

export interface UserSearchItemDto {
  id: string;
  type: string;
  name: string;
  /** @nullable */
  slug: string | null;
  /** @nullable */
  imageUrl: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  metadata: string | null;
  username: string;
  /** @nullable */
  displayName: string | null;
  visibility: string;
}

/**
 * Search type (prefix-based)
 */
export type SearchResultDtoSearchType = typeof SearchResultDtoSearchType[keyof typeof SearchResultDtoSearchType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchResultDtoSearchType = {
  global: 'global',
  user: 'user',
  club: 'club',
} as const;

export interface SearchResultDto {
  /** Search query used */
  query: string;
  /** Search type (prefix-based) */
  searchType: SearchResultDtoSearchType;
  /** Brands found (global search only) */
  brands?: BrandSearchItemDto[];
  /** Cigars found (global search only) */
  cigars?: CigarSearchItemDto[];
  /** Clubs found */
  clubs?: ClubSearchItemDto[];
  /** Users found */
  users?: UserSearchItemDto[];
  /** Total results count */
  total: number;
  /** Search duration in milliseconds */
  duration: number;
}

/**
 * @nullable
 */
export type BrandResponseDtoCountry = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type BrandResponseDtoDescription = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type BrandResponseDtoLogoUrl = { [key: string]: unknown } | null;

export interface BrandResponseDto {
  id: string;
  name: string;
  slug: string;
  /** @nullable */
  country: BrandResponseDtoCountry;
  /** @nullable */
  description: BrandResponseDtoDescription;
  /** @nullable */
  logoUrl: BrandResponseDtoLogoUrl;
  isVerified: boolean;
  createdAt: string;
}

export interface CigarResponseDto {
  id: string;
  name: string;
  slug: string;
  vitola: string;
  strength: number;
  brand: BrandResponseDto;
  isVerified: boolean;
  status: string;
  createdAt: string;
}

export interface CreateCigarDto {
  /** Brand name (will be created if not exists) */
  brandName: string;
  /** Brand country (only for new brands) */
  brandCountry?: string;
  /** Cigar name */
  name: string;
  /** Cigar vitola (format) */
  vitola: string;
  /** Cigar strength (1-5) */
  strength: number;
}

/**
 * Time of day
 */
export type CreateTastingDtoMoment = typeof CreateTastingDtoMoment[keyof typeof CreateTastingDtoMoment];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateTastingDtoMoment = {
  MATIN: 'MATIN',
  APRES_MIDI: 'APRES_MIDI',
  SOIR: 'SOIR',
} as const;

/**
 * Tasting situation
 */
export type CreateTastingDtoSituation = typeof CreateTastingDtoSituation[keyof typeof CreateTastingDtoSituation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateTastingDtoSituation = {
  APERITIF: 'APERITIF',
  COCKTAIL: 'COCKTAIL',
  DIGESTIF: 'DIGESTIF',
} as const;

/**
 * Beverage pairing type
 */
export type CreateTastingDtoPairing = typeof CreateTastingDtoPairing[keyof typeof CreateTastingDtoPairing];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateTastingDtoPairing = {
  WHISKY: 'WHISKY',
  RHUM: 'RHUM',
  COGNAC: 'COGNAC',
  CAFE: 'CAFE',
  THE: 'THE',
  EAU: 'EAU',
  VIN: 'VIN',
  BIERE: 'BIERE',
  AUTRE: 'AUTRE',
} as const;

export interface CreateTastingDto {
  /** UUID of the cigar being tasted */
  cigarId: string;
  /** UUID of the club to associate this tasting with */
  clubId?: string;
  /** UUID of the event (if tasting during an event) */
  eventId?: string;
  /** Time of day */
  moment?: CreateTastingDtoMoment;
  /** Tasting situation */
  situation?: CreateTastingDtoSituation;
  /** Beverage pairing type */
  pairing?: CreateTastingDtoPairing;
  /** Pairing details (e.g., "Lagavulin 16") */
  pairingNote?: string;
  /** Location (for solo tastings only) */
  location?: string;
  /** Photo URL */
  photoUrl?: string;
  /**
   * Duration in minutes
   * @minimum 1
   * @maximum 300
   */
  duration?: number;
}

export type ObservationResponseDtoOrganoleptic = { [key: string]: unknown };

export interface ObservationResponseDto {
  id: string;
  tastingId: string;
  /** Phase: presentation | fumage_cru | foin | divin | purin | conclusion */
  phase: string;
  intensity?: number;
  combustion?: number;
  aromas?: string[];
  notes?: string;
  organoleptic?: ObservationResponseDtoOrganoleptic;
  createdAt: string;
  updatedAt: string;
}

export interface TastingClubDto {
  id: string;
  name: string;
  slug: string;
}

export type TastingResponseDtoStatus = typeof TastingResponseDtoStatus[keyof typeof TastingResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingResponseDtoStatus = {
  DRAFT: 'DRAFT',
  COMPLETED: 'COMPLETED',
} as const;

export type TastingResponseDtoMoment = typeof TastingResponseDtoMoment[keyof typeof TastingResponseDtoMoment];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingResponseDtoMoment = {
  MATIN: 'MATIN',
  APRES_MIDI: 'APRES_MIDI',
  SOIR: 'SOIR',
} as const;

export type TastingResponseDtoSituation = typeof TastingResponseDtoSituation[keyof typeof TastingResponseDtoSituation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingResponseDtoSituation = {
  APERITIF: 'APERITIF',
  COCKTAIL: 'COCKTAIL',
  DIGESTIF: 'DIGESTIF',
} as const;

export type TastingResponseDtoPairing = typeof TastingResponseDtoPairing[keyof typeof TastingResponseDtoPairing];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingResponseDtoPairing = {
  WHISKY: 'WHISKY',
  RHUM: 'RHUM',
  COGNAC: 'COGNAC',
  CAFE: 'CAFE',
  THE: 'THE',
  EAU: 'EAU',
  VIN: 'VIN',
  BIERE: 'BIERE',
  AUTRE: 'AUTRE',
} as const;

export type TastingResponseDtoVisibility = typeof TastingResponseDtoVisibility[keyof typeof TastingResponseDtoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingResponseDtoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  CLUB_ONLY: 'CLUB_ONLY',
} as const;

export interface TastingResponseDto {
  id: string;
  userId: string;
  cigarId: string;
  cigar: CigarResponseDto;
  eventId?: string;
  status: TastingResponseDtoStatus;
  date: string;
  moment?: TastingResponseDtoMoment;
  situation?: TastingResponseDtoSituation;
  pairing?: TastingResponseDtoPairing;
  pairingNote?: string;
  location?: string;
  photoUrl?: string;
  duration?: number;
  rating: number;
  comment?: string;
  visibility: TastingResponseDtoVisibility;
  createdAt: string;
  updatedAt: string;
  /** Tasting observations by phase (chronic mode) */
  observations: ObservationResponseDto[];
  /** Clubs this tasting is shared with */
  clubs: TastingClubDto[];
}

export interface PaginatedTastingResponseDto {
  /** Array of tastings */
  data: TastingResponseDto[];
  /** Pagination metadata */
  meta: PaginationMetaDto;
}

/**
 * Time of day
 */
export type UpdateTastingDtoMoment = typeof UpdateTastingDtoMoment[keyof typeof UpdateTastingDtoMoment];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateTastingDtoMoment = {
  MATIN: 'MATIN',
  APRES_MIDI: 'APRES_MIDI',
  SOIR: 'SOIR',
} as const;

/**
 * Tasting situation
 */
export type UpdateTastingDtoSituation = typeof UpdateTastingDtoSituation[keyof typeof UpdateTastingDtoSituation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateTastingDtoSituation = {
  APERITIF: 'APERITIF',
  COCKTAIL: 'COCKTAIL',
  DIGESTIF: 'DIGESTIF',
} as const;

/**
 * Beverage pairing type
 */
export type UpdateTastingDtoPairing = typeof UpdateTastingDtoPairing[keyof typeof UpdateTastingDtoPairing];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateTastingDtoPairing = {
  WHISKY: 'WHISKY',
  RHUM: 'RHUM',
  COGNAC: 'COGNAC',
  CAFE: 'CAFE',
  THE: 'THE',
  EAU: 'EAU',
  VIN: 'VIN',
  BIERE: 'BIERE',
  AUTRE: 'AUTRE',
} as const;

export interface UpdateTastingDto {
  /** UUID of the cigar being tasted */
  cigarId?: string;
  /** UUID of the club to associate this tasting with */
  clubId?: string;
  /** UUID of the event (if tasting during an event) */
  eventId?: string;
  /** Time of day */
  moment?: UpdateTastingDtoMoment;
  /** Tasting situation */
  situation?: UpdateTastingDtoSituation;
  /** Beverage pairing type */
  pairing?: UpdateTastingDtoPairing;
  /** Pairing details (e.g., "Lagavulin 16") */
  pairingNote?: string;
  /** Location (for solo tastings only) */
  location?: string;
  /** Photo URL */
  photoUrl?: string;
  /**
   * Duration in minutes
   * @minimum 1
   * @maximum 300
   */
  duration?: number;
}

/**
 * Tasting visibility
 */
export type CompleteTastingDtoVisibility = typeof CompleteTastingDtoVisibility[keyof typeof CompleteTastingDtoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompleteTastingDtoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  CLUB_ONLY: 'CLUB_ONLY',
} as const;

export interface CompleteTastingDto {
  /**
   * Rating from 0.5 to 5 (by steps of 0.5)
   * @minimum 0.5
   * @maximum 5
   */
  rating: number;
  /** Global comment about the tasting */
  comment?: string;
  /** Tasting visibility */
  visibility?: CompleteTastingDtoVisibility;
}

/**
 * Detailed organoleptic profile (JSON)
 */
export type UpsertObservationDtoOrganoleptic = { [key: string]: unknown };

export interface UpsertObservationDto {
  /**
   * Aroma intensity (1-5)
   * @minimum 1
   * @maximum 5
   */
  intensity?: number;
  /**
   * Combustion quality (1-5)
   * @minimum 1
   * @maximum 5
   */
  combustion?: number;
  /** Detected aromas (simple array) */
  aromas?: string[];
  /** Free-form notes */
  notes?: string;
  /** Detailed organoleptic profile (JSON) */
  organoleptic?: UpsertObservationDtoOrganoleptic;
}

/**
 * Type of feedback
 */
export type CreateFeedbackDtoType = typeof CreateFeedbackDtoType[keyof typeof CreateFeedbackDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateFeedbackDtoType = {
  BUG: 'BUG',
  FEATURE: 'FEATURE',
  OTHER: 'OTHER',
} as const;

/**
 * Client metadata (auto-collected)
 */
export type CreateFeedbackDtoMetadata = { [key: string]: unknown };

export interface CreateFeedbackDto {
  /** Type of feedback */
  type: CreateFeedbackDtoType;
  /**
   * Feedback message
   * @maxLength 2000
   */
  message: string;
  /**
   * Page URL where the feedback was submitted
   * @maxLength 255
   */
  page: string;
  /** Client metadata (auto-collected) */
  metadata?: CreateFeedbackDtoMetadata;
}

export type FeedbackUserDtoAvatarUrl = { [key: string]: unknown };

export interface FeedbackUserDto {
  id: string;
  username: string;
  displayName: string;
  avatarUrl?: FeedbackUserDtoAvatarUrl;
}

export type FeedbackResponseDtoType = typeof FeedbackResponseDtoType[keyof typeof FeedbackResponseDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeedbackResponseDtoType = {
  BUG: 'BUG',
  FEATURE: 'FEATURE',
  OTHER: 'OTHER',
} as const;

export type FeedbackResponseDtoMetadata = { [key: string]: unknown };

export type FeedbackResponseDtoStatus = typeof FeedbackResponseDtoStatus[keyof typeof FeedbackResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeedbackResponseDtoStatus = {
  NEW: 'NEW',
  READ: 'READ',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  WONT_FIX: 'WONT_FIX',
} as const;

export type FeedbackResponseDtoAdminNote = { [key: string]: unknown };

export interface FeedbackResponseDto {
  id: string;
  userId: string;
  type: FeedbackResponseDtoType;
  message: string;
  page: string;
  metadata?: FeedbackResponseDtoMetadata;
  status: FeedbackResponseDtoStatus;
  adminNote?: FeedbackResponseDtoAdminNote;
  createdAt: string;
  updatedAt: string;
  user?: FeedbackUserDto;
}

export interface PaginationMeta {
  total: number;
  page: number;
  limit: number;
}

export interface PaginatedFeedbackResponseDto {
  data: FeedbackResponseDto[];
  meta: PaginationMeta;
}

/**
 * New status for the feedback
 */
export type UpdateFeedbackStatusDtoStatus = typeof UpdateFeedbackStatusDtoStatus[keyof typeof UpdateFeedbackStatusDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateFeedbackStatusDtoStatus = {
  NEW: 'NEW',
  READ: 'READ',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  WONT_FIX: 'WONT_FIX',
} as const;

export interface UpdateFeedbackStatusDto {
  /** New status for the feedback */
  status: UpdateFeedbackStatusDtoStatus;
  /**
   * Admin note (internal)
   * @maxLength 1000
   */
  adminNote?: string;
}

/**
 * Event-specific data
 */
export type TrackEventDtoData = { [key: string]: unknown };

export interface TrackEventDto {
  /**
   * Event name (lowercase snake_case)
   * @maxLength 100
   */
  event: string;
  /** Event-specific data */
  data?: TrackEventDtoData;
  /**
   * Page URL where the event occurred
   * @maxLength 255
   */
  page: string;
  /**
   * Platform (desktop, android, ios, web)
   * @maxLength 50
   */
  platform?: string;
  /** Screen width in pixels */
  screenWidth?: number;
  /** Screen height in pixels */
  screenHeight?: number;
}

export type AnalyticsEventUserDtoAvatarUrl = { [key: string]: unknown };

export interface AnalyticsEventUserDto {
  id: string;
  username: string;
  displayName: string;
  avatarUrl?: AnalyticsEventUserDtoAvatarUrl;
}

export type AnalyticsEventResponseDtoUserId = { [key: string]: unknown };

/**
 * Event-specific data
 */
export type AnalyticsEventResponseDtoData = { [key: string]: unknown };

export type AnalyticsEventResponseDtoPlatform = { [key: string]: unknown };

export type AnalyticsEventResponseDtoScreenWidth = { [key: string]: unknown };

export type AnalyticsEventResponseDtoScreenHeight = { [key: string]: unknown };

export interface AnalyticsEventResponseDto {
  id: string;
  userId?: AnalyticsEventResponseDtoUserId;
  event: string;
  /** Event-specific data */
  data?: AnalyticsEventResponseDtoData;
  page: string;
  platform?: AnalyticsEventResponseDtoPlatform;
  screenWidth?: AnalyticsEventResponseDtoScreenWidth;
  screenHeight?: AnalyticsEventResponseDtoScreenHeight;
  createdAt: string;
  user?: AnalyticsEventUserDto;
}

export interface PaginatedAnalyticsEventsDto {
  data: AnalyticsEventResponseDto[];
  meta: PaginationMeta;
}

export interface EventCountDto {
  event: string;
  count: number;
}

export interface DailyCountDto {
  date: string;
  count: number;
}

export interface PlatformCountDto {
  platform: string;
  count: number;
}

export interface AnalyticsSummaryDto {
  totalEvents: number;
  uniqueUsers: number;
  eventCounts: EventCountDto[];
  dailyCounts: DailyCountDto[];
  platformCounts: PlatformCountDto[];
}

export interface PlatformStatsDto {
  totalUsers: number;
  totalClubs: number;
  totalTastings: number;
  totalEvents: number;
}

export interface DiscoverCigarDto {
  id: string;
  name: string;
  slug: string;
  brandName: string;
  createdAt: string;
}

export interface DiscoverTastingDto {
  id: string;
  cigarName: string;
  cigarSlug: string;
  rating: number;
  username: string;
  createdAt: string;
}

export interface DiscoverResponseDto {
  /** Recently added cigars (newest first) */
  recentCigars: DiscoverCigarDto[];
  /** Recent public tastings (newest first) */
  recentTastings: DiscoverTastingDto[];
}

export type ClubControllerFindAllParams = {
/**
 * Page number
 * @minimum 1
 */
page?: number;
/**
 * Items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Search in club name
 */
search?: string;
/**
 * Sort by field
 */
sortBy?: ClubControllerFindAllSortBy;
/**
 * Sort order
 */
order?: ClubControllerFindAllOrder;
};

export type ClubControllerFindAllSortBy = typeof ClubControllerFindAllSortBy[keyof typeof ClubControllerFindAllSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClubControllerFindAllSortBy = {
  name: 'name',
  createdAt: 'createdAt',
} as const;

export type ClubControllerFindAllOrder = typeof ClubControllerFindAllOrder[keyof typeof ClubControllerFindAllOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClubControllerFindAllOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ClubControllerUploadAvatarBody = {
  /** Image file (JPEG, PNG, WebP, max 5MB) */
  avatar?: Blob;
};

export type ClubControllerUploadAvatar200 = {
  imageUrl?: string;
};

export type ClubControllerGetMembersParams = {
page: number;
limit: number;
};

export type ClubControllerGetBannedMembersParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
};

export type ClubControllerGetJoinRequestsParams = {
page: number;
limit: number;
status: string;
};

export type UsersControllerGetUserClubsParams = {
/**
 * Maximum number of clubs to return
 */
limit?: number;
};

export type UsersControllerUploadAvatarBody = {
  /** Image file (JPEG, PNG, WebP, max 5MB) */
  avatar?: Blob;
};

export type UsersControllerUploadAvatar200 = {
  avatarUrl?: string;
};

export type UsersControllerCheckUsernameAvailabilityParams = {
/**
 * Current user ID to exclude from check (when updating own profile)
 */
currentUserId?: string;
};

export type UsersControllerCheckUsernameAvailability200 = {
  available?: boolean;
};

export type SearchControllerSearchParams = {
/**
 * Search query with optional prefix (@ for users, # for clubs)
 * @minLength 1
 * @maxLength 100
 */
q: string;
};

export type BrandControllerFindAllParams = {
/**
 * Search brands by name or slug (case-insensitive)
 */
search?: string;
};

export type TastingControllerFindMineParams = {
/**
 * Page number
 * @minimum 1
 */
page?: number;
/**
 * Items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Sort by field
 */
sortBy?: TastingControllerFindMineSortBy;
/**
 * Sort order
 */
order?: TastingControllerFindMineOrder;
/**
 * Filter by status
 */
status?: TastingControllerFindMineStatus;
/**
 * Filter by cigar ID
 */
cigarId?: string;
/**
 * Filter by user ID
 */
userId?: string;
/**
 * Filter by event ID
 */
eventId?: string;
};

export type TastingControllerFindMineSortBy = typeof TastingControllerFindMineSortBy[keyof typeof TastingControllerFindMineSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingControllerFindMineSortBy = {
  date: 'date',
  rating: 'rating',
  createdAt: 'createdAt',
} as const;

export type TastingControllerFindMineOrder = typeof TastingControllerFindMineOrder[keyof typeof TastingControllerFindMineOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingControllerFindMineOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type TastingControllerFindMineStatus = typeof TastingControllerFindMineStatus[keyof typeof TastingControllerFindMineStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingControllerFindMineStatus = {
  DRAFT: 'DRAFT',
  COMPLETED: 'COMPLETED',
} as const;

export type TastingControllerFindByCigarParams = {
/**
 * Page number
 * @minimum 1
 */
page?: number;
/**
 * Items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Sort by field
 */
sortBy?: TastingControllerFindByCigarSortBy;
/**
 * Sort order
 */
order?: TastingControllerFindByCigarOrder;
/**
 * Filter by status
 */
status?: TastingControllerFindByCigarStatus;
/**
 * Filter by user ID
 */
userId?: string;
/**
 * Filter by event ID
 */
eventId?: string;
};

export type TastingControllerFindByCigarSortBy = typeof TastingControllerFindByCigarSortBy[keyof typeof TastingControllerFindByCigarSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingControllerFindByCigarSortBy = {
  date: 'date',
  rating: 'rating',
  createdAt: 'createdAt',
} as const;

export type TastingControllerFindByCigarOrder = typeof TastingControllerFindByCigarOrder[keyof typeof TastingControllerFindByCigarOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingControllerFindByCigarOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type TastingControllerFindByCigarStatus = typeof TastingControllerFindByCigarStatus[keyof typeof TastingControllerFindByCigarStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingControllerFindByCigarStatus = {
  DRAFT: 'DRAFT',
  COMPLETED: 'COMPLETED',
} as const;

export type TastingControllerFindByClubParams = {
/**
 * Page number
 * @minimum 1
 */
page?: number;
/**
 * Items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Sort by field
 */
sortBy?: TastingControllerFindByClubSortBy;
/**
 * Sort order
 */
order?: TastingControllerFindByClubOrder;
/**
 * Filter by status
 */
status?: TastingControllerFindByClubStatus;
/**
 * Filter by cigar ID
 */
cigarId?: string;
/**
 * Filter by user ID
 */
userId?: string;
/**
 * Filter by event ID
 */
eventId?: string;
};

export type TastingControllerFindByClubSortBy = typeof TastingControllerFindByClubSortBy[keyof typeof TastingControllerFindByClubSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingControllerFindByClubSortBy = {
  date: 'date',
  rating: 'rating',
  createdAt: 'createdAt',
} as const;

export type TastingControllerFindByClubOrder = typeof TastingControllerFindByClubOrder[keyof typeof TastingControllerFindByClubOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingControllerFindByClubOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type TastingControllerFindByClubStatus = typeof TastingControllerFindByClubStatus[keyof typeof TastingControllerFindByClubStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TastingControllerFindByClubStatus = {
  DRAFT: 'DRAFT',
  COMPLETED: 'COMPLETED',
} as const;

export type FeedbackControllerFindAllParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
/**
 * Filter by status
 */
status?: FeedbackControllerFindAllStatus;
/**
 * Filter by type
 */
type?: FeedbackControllerFindAllType;
/**
 * Sort by field
 */
sortBy?: string;
/**
 * Sort order
 */
order?: string;
};

export type FeedbackControllerFindAllStatus = typeof FeedbackControllerFindAllStatus[keyof typeof FeedbackControllerFindAllStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeedbackControllerFindAllStatus = {
  NEW: 'NEW',
  READ: 'READ',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  WONT_FIX: 'WONT_FIX',
} as const;

export type FeedbackControllerFindAllType = typeof FeedbackControllerFindAllType[keyof typeof FeedbackControllerFindAllType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeedbackControllerFindAllType = {
  BUG: 'BUG',
  FEATURE: 'FEATURE',
  OTHER: 'OTHER',
} as const;

export type AnalyticsControllerFindAllParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
/**
 * Filter by event name
 */
event?: string;
/**
 * Filter by user ID
 */
userId?: string;
/**
 * Sort by field
 */
sortBy?: string;
/**
 * Sort order
 */
order?: AnalyticsControllerFindAllOrder;
};

export type AnalyticsControllerFindAllOrder = typeof AnalyticsControllerFindAllOrder[keyof typeof AnalyticsControllerFindAllOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalyticsControllerFindAllOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

