/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
export interface SignUpDto {
  /** User email address */
  email: string;
  /**
   * User password (min 8 characters)
   * @minLength 8
   */
  password: string;
  /** User display name */
  displayName: string;
}

export type UserDtoRole = typeof UserDtoRole[keyof typeof UserDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDtoRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  MODERATOR: 'MODERATOR',
  USER: 'USER',
} as const;

/**
 * Authentication provider (from Supabase metadata)
 */
export type UserDtoAuthProvider = typeof UserDtoAuthProvider[keyof typeof UserDtoAuthProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDtoAuthProvider = {
  google: 'google',
  apple: 'apple',
  email: 'email',
} as const;

export interface UserDto {
  id: string;
  email: string;
  displayName: string;
  avatarUrl?: string;
  role: UserDtoRole;
  createdAt: string;
  /** Authentication provider (from Supabase metadata) */
  authProvider?: UserDtoAuthProvider;
}

/**
 * Supabase session with access token, refresh token, and expiry info
 */
export type AuthResponseDtoSession = { [key: string]: unknown };

export interface AuthResponseDto {
  user: UserDto;
  /** Supabase session with access token, refresh token, and expiry info */
  session: AuthResponseDtoSession;
}

export interface SignInDto {
  /** User email address */
  email: string;
  /** User password */
  password: string;
}

export interface UpdateProfileDto {
  /** Display name of the user */
  displayName?: string;
  /** Avatar URL */
  avatarUrl?: string;
}

export interface CreateClubDto {
  /**
   * Club name
   * @minLength 3
   * @maxLength 100
   */
  name: string;
  /**
   * Club description
   * @maxLength 1000
   */
  description?: string;
  /** Club image URL */
  imageUrl?: string;
}

export type ClubResponseDtoDescription = { [key: string]: unknown };

export type ClubResponseDtoImageUrl = { [key: string]: unknown };

export interface ClubResponseDto {
  id: string;
  name: string;
  description?: ClubResponseDtoDescription;
  imageUrl?: ClubResponseDtoImageUrl;
  createdBy: string;
  createdAt: string;
}

export interface UpdateClubDto { [key: string]: unknown }

export type ClubControllerFindAllParams = {
/**
 * Page number
 * @minimum 1
 */
page?: number;
/**
 * Items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Search in club name
 */
search?: string;
/**
 * Sort by field
 */
sortBy?: ClubControllerFindAllSortBy;
/**
 * Sort order
 */
order?: ClubControllerFindAllOrder;
};

export type ClubControllerFindAllSortBy = typeof ClubControllerFindAllSortBy[keyof typeof ClubControllerFindAllSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClubControllerFindAllSortBy = {
  name: 'name',
  createdAt: 'createdAt',
} as const;

export type ClubControllerFindAllOrder = typeof ClubControllerFindAllOrder[keyof typeof ClubControllerFindAllOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClubControllerFindAllOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type UsersControllerUploadAvatarBody = {
  /** Image file (JPEG, PNG, WebP, max 5MB) */
  avatar?: Blob;
};

export type UsersControllerUploadAvatar200 = {
  avatarUrl?: string;
};

