/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
export interface SignUpDto {
  /** User email address */
  email: string;
  /**
   * User password (min 8 characters)
   * @minLength 8
   */
  password: string;
  /** User display name */
  displayName: string;
}

export type UserDtoRole = typeof UserDtoRole[keyof typeof UserDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDtoRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  MODERATOR: 'MODERATOR',
  USER: 'USER',
} as const;

/**
 * Authentication provider (from Supabase metadata)
 */
export type UserDtoAuthProvider = typeof UserDtoAuthProvider[keyof typeof UserDtoAuthProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDtoAuthProvider = {
  google: 'google',
  apple: 'apple',
  email: 'email',
} as const;

export interface UserDto {
  id: string;
  email: string;
  displayName: string;
  avatarUrl?: string;
  role: UserDtoRole;
  createdAt: string;
  /** Authentication provider (from Supabase metadata) */
  authProvider?: UserDtoAuthProvider;
}

/**
 * Supabase session with access token, refresh token, and expiry info
 */
export type AuthResponseDtoSession = { [key: string]: unknown };

export interface AuthResponseDto {
  user: UserDto;
  /** Supabase session with access token, refresh token, and expiry info */
  session: AuthResponseDtoSession;
}

export interface SignInDto {
  /** User email address */
  email: string;
  /** User password */
  password: string;
}

export interface UpdateProfileDto {
  /** Display name of the user */
  displayName?: string;
  /** Avatar URL */
  avatarUrl?: string;
}

/**
 * Club visibility
 */
export type CreateClubDtoVisibility = typeof CreateClubDtoVisibility[keyof typeof CreateClubDtoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateClubDtoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
} as const;

export interface CreateClubDto {
  /**
   * Club name
   * @minLength 3
   * @maxLength 100
   */
  name: string;
  /**
   * Club description
   * @maxLength 1000
   */
  description?: string;
  /** Club avatar image URL */
  imageUrl?: string;
  /** Club cover image URL */
  coverUrl?: string;
  /** Club visibility */
  visibility?: CreateClubDtoVisibility;
  /** Auto-approve join requests */
  autoApproveMembers?: boolean;
  /** Allow members to invite others */
  allowMemberInvites?: boolean;
  /** Maximum number of members (null = unlimited) */
  maxMembers?: number;
  /** Show in public directory (even if PRIVATE) */
  isPublicDirectory?: boolean;
}

export type ClubResponseDtoDescription = { [key: string]: unknown };

export type ClubResponseDtoImageUrl = { [key: string]: unknown };

export type ClubResponseDtoCoverUrl = { [key: string]: unknown };

export type ClubResponseDtoVisibility = typeof ClubResponseDtoVisibility[keyof typeof ClubResponseDtoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClubResponseDtoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
} as const;

/**
 * Only returned for club owners/admins
 */
export type ClubResponseDtoInviteCode = { [key: string]: unknown };

export type ClubResponseDtoMaxMembers = { [key: string]: unknown };

export interface ClubResponseDto {
  id: string;
  name: string;
  description?: ClubResponseDtoDescription;
  imageUrl?: ClubResponseDtoImageUrl;
  coverUrl?: ClubResponseDtoCoverUrl;
  visibility: ClubResponseDtoVisibility;
  /** Only returned for club owners/admins */
  inviteCode?: ClubResponseDtoInviteCode;
  isPublicDirectory: boolean;
  autoApproveMembers: boolean;
  allowMemberInvites: boolean;
  maxMembers?: ClubResponseDtoMaxMembers;
  isArchived: boolean;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  /** Total number of members in the club */
  memberCount: number;
}

/**
 * Club visibility
 */
export type UpdateClubDtoVisibility = typeof UpdateClubDtoVisibility[keyof typeof UpdateClubDtoVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateClubDtoVisibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
} as const;

export interface UpdateClubDto {
  /**
   * Club name
   * @minLength 3
   * @maxLength 100
   */
  name?: string;
  /**
   * Club description
   * @maxLength 1000
   */
  description?: string;
  /** Club avatar image URL */
  imageUrl?: string;
  /** Club cover image URL */
  coverUrl?: string;
  /** Club visibility */
  visibility?: UpdateClubDtoVisibility;
  /** Auto-approve join requests */
  autoApproveMembers?: boolean;
  /** Allow members to invite others */
  allowMemberInvites?: boolean;
  /** Maximum number of members (null = unlimited) */
  maxMembers?: number;
  /** Show in public directory (even if PRIVATE) */
  isPublicDirectory?: boolean;
}

/**
 * New role for the member
 */
export type UpdateMemberRoleDtoRole = typeof UpdateMemberRoleDtoRole[keyof typeof UpdateMemberRoleDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateMemberRoleDtoRole = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
} as const;

export interface UpdateMemberRoleDto {
  /** New role for the member */
  role: UpdateMemberRoleDtoRole;
}

export interface TransferOwnershipDto {
  /** User ID of the new owner */
  newOwnerId: string;
}

export interface BanMemberDto {
  /**
   * Reason for banning the member
   * @maxLength 500
   */
  reason?: string;
}

export interface CreateJoinRequestDto {
  /**
   * Optional message to club owner/admin
   * @maxLength 500
   */
  message?: string;
}

export interface JoinByCodeDto {
  /** Club invitation code */
  code?: string;
}

/**
 * Join request status
 */
export type UpdateJoinRequestDtoStatus = typeof UpdateJoinRequestDtoStatus[keyof typeof UpdateJoinRequestDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateJoinRequestDtoStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export interface UpdateJoinRequestDto {
  /** Join request status */
  status?: UpdateJoinRequestDtoStatus;
}

export type ClubControllerFindAllParams = {
/**
 * Page number
 * @minimum 1
 */
page?: number;
/**
 * Items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Search in club name
 */
search?: string;
/**
 * Sort by field
 */
sortBy?: ClubControllerFindAllSortBy;
/**
 * Sort order
 */
order?: ClubControllerFindAllOrder;
};

export type ClubControllerFindAllSortBy = typeof ClubControllerFindAllSortBy[keyof typeof ClubControllerFindAllSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClubControllerFindAllSortBy = {
  name: 'name',
  createdAt: 'createdAt',
} as const;

export type ClubControllerFindAllOrder = typeof ClubControllerFindAllOrder[keyof typeof ClubControllerFindAllOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClubControllerFindAllOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type ClubControllerGetMembersParams = {
page: number;
limit: number;
};

export type ClubControllerGetJoinRequestsParams = {
page: number;
limit: number;
status: string;
};

export type UsersControllerUploadAvatarBody = {
  /** Image file (JPEG, PNG, WebP, max 5MB) */
  avatar?: Blob;
};

export type UsersControllerUploadAvatar200 = {
  avatarUrl?: string;
};

