/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  DeepNonNullable
} from '@orval/core';

import type {
  CompleteTastingDto,
  CreateTastingDto,
  PaginatedTastingResponseDto,
  TastingControllerFindByCigarParams,
  TastingControllerFindByClubParams,
  TastingControllerFindMineParams,
  TastingResponseDto,
  UpdateTastingDto
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';






@Injectable({ providedIn: 'root' })
export class TastingsService {
  private readonly http = inject(HttpClient);
/**
 * @summary Create a new tasting (DRAFT)
 */
 tastingControllerCreate<TData = TastingResponseDto>(
    createTastingDto: CreateTastingDto,
 ) {
      return customInstance<TData>(
      {url: `/api/tastings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTastingDto
    },
      this.http,
      );
    }
  /**
 * @summary Get my tastings (paginated)
 */
 tastingControllerFindMine<TData = PaginatedTastingResponseDto>(
    params?: DeepNonNullable<TastingControllerFindMineParams>,
 ) {
      return customInstance<TData>(
      {url: `/api/tastings/me`, method: 'GET',
        params
    },
      this.http,
      );
    }
  /**
 * @summary Get tastings for a cigar (paginated)
 */
 tastingControllerFindByCigar<TData = PaginatedTastingResponseDto>(
    cigarId: string,
    params?: DeepNonNullable<TastingControllerFindByCigarParams>,
 ) {
      return customInstance<TData>(
      {url: `/api/tastings/cigar/${cigarId}`, method: 'GET',
        params
    },
      this.http,
      );
    }
  /**
 * @summary Get tastings shared with a club (paginated)
 */
 tastingControllerFindByClub<TData = PaginatedTastingResponseDto>(
    clubId: string,
    params?: DeepNonNullable<TastingControllerFindByClubParams>,
 ) {
      return customInstance<TData>(
      {url: `/api/tastings/club/${clubId}`, method: 'GET',
        params
    },
      this.http,
      );
    }
  /**
 * @summary Get tasting by ID
 */
 tastingControllerFindOne<TData = TastingResponseDto>(
    id: string,
 ) {
      return customInstance<TData>(
      {url: `/api/tastings/${id}`, method: 'GET'
    },
      this.http,
      );
    }
  /**
 * @summary Update tasting (auto-save, DRAFT only)
 */
 tastingControllerUpdate<TData = TastingResponseDto>(
    id: string,
    updateTastingDto: UpdateTastingDto,
 ) {
      return customInstance<TData>(
      {url: `/api/tastings/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTastingDto
    },
      this.http,
      );
    }
  /**
 * @summary Delete tasting (author only)
 */
 tastingControllerRemove<TData = void>(
    id: string,
 ) {
      return customInstance<TData>(
      {url: `/api/tastings/${id}`, method: 'DELETE'
    },
      this.http,
      );
    }
  /**
 * @summary Complete tasting (DRAFT → COMPLETED, immutable after)
 */
 tastingControllerComplete<TData = TastingResponseDto>(
    id: string,
    completeTastingDto: CompleteTastingDto,
 ) {
      return customInstance<TData>(
      {url: `/api/tastings/${id}/complete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: completeTastingDto
    },
      this.http,
      );
    }
  };

export type TastingControllerCreateClientResult = NonNullable<TastingResponseDto>
export type TastingControllerFindMineClientResult = NonNullable<PaginatedTastingResponseDto>
export type TastingControllerFindByCigarClientResult = NonNullable<PaginatedTastingResponseDto>
export type TastingControllerFindByClubClientResult = NonNullable<PaginatedTastingResponseDto>
export type TastingControllerFindOneClientResult = NonNullable<TastingResponseDto>
export type TastingControllerUpdateClientResult = NonNullable<TastingResponseDto>
export type TastingControllerRemoveClientResult = NonNullable<void>
export type TastingControllerCompleteClientResult = NonNullable<TastingResponseDto>
