/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  DeepNonNullable
} from '@orval/core';

import type {
  CreateFeedbackDto,
  FeedbackControllerFindAllParams,
  FeedbackResponseDto,
  PaginatedFeedbackResponseDto,
  UpdateFeedbackStatusDto
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';






@Injectable({ providedIn: 'root' })
export class FeedbackService {
  private readonly http = inject(HttpClient);
/**
 * @summary Submit feedback
 */
 feedbackControllerCreate<TData = FeedbackResponseDto>(
    createFeedbackDto: CreateFeedbackDto,
 ) {
      return customInstance<TData>(
      {url: `/api/feedback`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFeedbackDto
    },
      this.http,
      );
    }
  /**
 * @summary Get all feedbacks (admin only)
 */
 feedbackControllerFindAll<TData = PaginatedFeedbackResponseDto>(
    params?: DeepNonNullable<FeedbackControllerFindAllParams>,
 ) {
      return customInstance<TData>(
      {url: `/api/feedback`, method: 'GET',
        params
    },
      this.http,
      );
    }
  /**
 * @summary Update feedback status (admin only)
 */
 feedbackControllerUpdateStatus<TData = FeedbackResponseDto>(
    id: string,
    updateFeedbackStatusDto: UpdateFeedbackStatusDto,
 ) {
      return customInstance<TData>(
      {url: `/api/feedback/${id}/status`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateFeedbackStatusDto
    },
      this.http,
      );
    }
  };

export type FeedbackControllerCreateClientResult = NonNullable<FeedbackResponseDto>
export type FeedbackControllerFindAllClientResult = NonNullable<PaginatedFeedbackResponseDto>
export type FeedbackControllerUpdateStatusClientResult = NonNullable<FeedbackResponseDto>
