/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  DeepNonNullable
} from '@orval/core';

import type {
  SearchControllerSearchParams,
  SearchResultDto
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';






@Injectable({ providedIn: 'root' })
export class SearchService {
  private readonly http = inject(HttpClient);
/**
 * 
Search across all entities with optional prefix filtering:
- No prefix: Global search (brands, cigars, PUBLIC clubs, users)
- @username: Search users only
- #slug: Search clubs only

Features:
- Case-insensitive contains search
- Max 8 results per category
- PRIVATE clubs excluded from global search
- PRIVATE users show only @username (displayName hidden)
- VERIFIED cigars only
- Performance optimized (<100ms target)
    
 * @summary Universal search (Omnisearch)
 */
 searchControllerSearch<TData = SearchResultDto>(
    params: DeepNonNullable<SearchControllerSearchParams>,
 ) {
      return customInstance<TData>(
      {url: `/api/search`, method: 'GET',
        params
    },
      this.http,
      );
    }
  };

export type SearchControllerSearchClientResult = NonNullable<SearchResultDto>
