/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  DiscoverResponseDto
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';






@Injectable({ providedIn: 'root' })
export class DiscoverService {
  private readonly http = inject(HttpClient);
/**
 * 
Returns discovery content for the explore page:
- Recent cigars: 3 most recently added cigars with brand info
- Recent tastings: 6 most recent PUBLIC, COMPLETED tastings with user info

Features:
- No authentication required
- Optimized for fast loading
- Only shows public content
    
 * @summary Get discovery content for explore page
 */
 discoverControllerGetDiscoveryContent<TData = DiscoverResponseDto>(
    
 ) {
      return customInstance<TData>(
      {url: `/api/discover`, method: 'GET'
    },
      this.http,
      );
    }
  };

export type DiscoverControllerGetDiscoveryContentClientResult = NonNullable<DiscoverResponseDto>
