/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  DeepNonNullable
} from '@orval/core';

import type {
  DiscoverControllerGetPublicTastingsParams,
  DiscoverResponseDto,
  PaginatedTastingResponseDto
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';






@Injectable({ providedIn: 'root' })
export class DiscoverService {
  private readonly http = inject(HttpClient);
/**
 * 
Returns discovery content for the explore page:
- Recent cigars: 3 most recently added cigars with brand info
- Recent tastings: 6 most recent PUBLIC, COMPLETED tastings with user info

Features:
- No authentication required
- Optimized for fast loading
- Only shows public content
    
 * @summary Get discovery content for explore page
 */
 discoverControllerGetDiscoveryContent<TData = DiscoverResponseDto>(
    
 ) {
      return customInstance<TData>(
      {url: `/api/discover`, method: 'GET'
    },
      this.http,
      );
    }
  /**
 * 
Returns paginated public tastings for the discovery feed:
- All PUBLIC, COMPLETED tastings from all users
- Ordered by date (newest first)
- Includes user info for display in global context
- 9 items per page by default

Features:
- No authentication required
- Infinite scroll support
- Optimized for mobile grid display
    
 * @summary Get public tastings with pagination
 */
 discoverControllerGetPublicTastings<TData = PaginatedTastingResponseDto>(
    params?: DeepNonNullable<DiscoverControllerGetPublicTastingsParams>,
 ) {
      return customInstance<TData>(
      {url: `/api/discover/tastings`, method: 'GET',
        params
    },
      this.http,
      );
    }
  };

export type DiscoverControllerGetDiscoveryContentClientResult = NonNullable<DiscoverResponseDto>
export type DiscoverControllerGetPublicTastingsClientResult = NonNullable<PaginatedTastingResponseDto>
