/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cigar Platform API
 * API for cigar tasting club management
 * OpenAPI spec version: 1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  DeepNonNullable
} from '@orval/core';

import type {
  AnalyticsControllerFindAllParams,
  AnalyticsSummaryDto,
  PaginatedAnalyticsEventsDto,
  PlatformStatsDto,
  TrackEventDto
} from '../generated-api.schemas';

import { customInstance } from '../../../../../apps/web/src/app/core/api/custom-instance';






@Injectable({ providedIn: 'root' })
export class AnalyticsService {
  private readonly http = inject(HttpClient);
/**
 * @summary Track an analytics event
 */
 analyticsControllerTrack<TData = void>(
    trackEventDto: TrackEventDto,
 ) {
      return customInstance<TData>(
      {url: `/api/analytics/track`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: trackEventDto
    },
      this.http,
      );
    }
  /**
 * @summary Get all analytics events with pagination (admin only)
 */
 analyticsControllerFindAll<TData = PaginatedAnalyticsEventsDto>(
    params?: DeepNonNullable<AnalyticsControllerFindAllParams>,
 ) {
      return customInstance<TData>(
      {url: `/api/analytics/events`, method: 'GET',
        params
    },
      this.http,
      );
    }
  /**
 * @summary Get analytics summary (admin only)
 */
 analyticsControllerGetSummary<TData = AnalyticsSummaryDto>(
    
 ) {
      return customInstance<TData>(
      {url: `/api/analytics/summary`, method: 'GET'
    },
      this.http,
      );
    }
  /**
 * @summary Get platform stats (admin only)
 */
 analyticsControllerGetPlatformStats<TData = PlatformStatsDto>(
    
 ) {
      return customInstance<TData>(
      {url: `/api/analytics/stats`, method: 'GET'
    },
      this.http,
      );
    }
  };

export type AnalyticsControllerTrackClientResult = NonNullable<void>
export type AnalyticsControllerFindAllClientResult = NonNullable<PaginatedAnalyticsEventsDto>
export type AnalyticsControllerGetSummaryClientResult = NonNullable<AnalyticsSummaryDto>
export type AnalyticsControllerGetPlatformStatsClientResult = NonNullable<PlatformStatsDto>
